PREDEFINED_FIELDS = {
    "tdetl": {
        "record_descriptor": {
            "source": "predefined",
            "value": "TDETL",
            "type": "CONSTANT",
            "required": True,
            "start": 1,
            "end": 5,
            "length": 5,
        },
        "Line_ID": {
            "source": "sequence",
            "type": "SEQUENTIAL",
            "required": True,
            "start": 6,
            "end": 15,
            "length": 10,
            "format": "zero_padded",
        },
        "transaction_number": {
            "source": "Transaction",
            "type": "TRANSACTION_SEQUENCE",
            "required": True,
            "start": 16,
            "end": 25,
            "length": 10,
            "format": "ZERO_PADDED",
            "repeat_for_children": True,
        },
        "UPC": {
            "field_name": "UPC",
            "source": "WEB_SERVICE",
            "type": "Character",
            "required": True,
            "start": 26,
            "end": 50,
            "length": 25,
        },
        "UPC_Supplement": {
            "field_name": "UPC Supplement",
            "type": "Character",
            "required": False,
            "start": 51,
            "end": 55,
            "length": 5,
        },
        "Item": {
            "field_name": "Item",
            "source": "WEB_SERVICE",
            "type": "Character",
            "required": True,
            "start": 56,
            "end": 80,
            "length": 25,
        },
        "VPN": {
            "field_name": "VPN",
            "source": "WEB_SERVICE",
            "type": "Character",
            "required": True,
            "start": 81,
            "end": 110,
            "length": 30,
        },
        "Sign_Indicator_quantity": {
            "field_name": "sign_indicator",
            "source": "Predefined",
            "value": "+",
            "type": "sign",
            "required": True,
            "start": 111,
            "end": 111,
            "length": 1,
        },
        "original_document_quantity": {
            "field_name": "Quantity",
            "ocr_field": "quantity",
            "source": "OCR",
            "type": "Number",
            "required": True,
            "start": 112,
            "end": 123,
            "length": 12,
            "decimal_places": 4,
            "implied_decimals": True,
        },
        "sign_indicator_unit_cost": {
            "field_name": "Sign_indicator_unitcost",
            "source": "Predefined",
            "value": "+",
            "type": "sign",
            "required": True,
            "start": 124,
            "end": 124,
            "length": 1,
        },
        "original_unit_cost": {
            "field_name": "original_unit_cost",
            "ocr_field": "original_unit_cost",
            "source": "OCR",
            "type": "Number",
            "required": True,
            "start": 125,
            "end": 144,
            "length": 20,
            "decimal_places": 4,
            "implied_decimals": True,
        },
        "Orginal_vat_code": {
            "field_name": "original_vat_code",
            "source": "WEB_SERVICE",
            "type": "Character",
            "required": True,
            "start": 145,
            "end": 150,
            "length": 6,
        },
        "Orginal_vat_rate": {
            "field_name": "original_vat_rate",
            "source": "WEB_SERVICE",
            "type": "Number",
            "required": True,
            "start": 151,
            "end": 170,
            "length": 20,
            "decimal_places": 4,
            "implied_decimals": True,
        },
        "Sign_indicator_Total_Allowance": {
            "field_name": "sign_indicator_Total_Allowance",
            "source": "Predefined",
            "value": "+",
            "type": "sign",
            "required": True,
            "start": 171,
            "end": 171,
            "length": 1,
        },
        "Total_Allowance": {
            "field_name": "Total_Allowance",
            "type": "Number",
            "required": False,
            "start": 172,
            "end": 191,
            "length": 20,
            "decimal_places": 4,
            "implied_decimals": True,
        },
    },
}
