PREDEFINED_FIELDS = {
    "thead": {
        "record_descriptor": {
            "source": "predefined",
            "value": "THEAD",
            "type": "CONSTANT",
            "required": True,
            "start": 1,
            "end": 5,
            "length": 5,
        },
        "Line_ID": {
            "source": "sequence",
            "type": "SEQUENTIAL",
            "required": True,
            "start": 6,
            "end": 15,
            "length": 10,
            "format": "zero_padded",
        },
        "transaction_number": {
            "source": "Transaction",
            "type": "TRANSACTION_SEQUENCE",
            "required": True,
            "start": 16,
            "end": 25,
            "length": 10,
            "format": "ZERO_PADDED",
            "repeat_for_children": True,
        },
        "Document_Type": {
            "source": "predefined",
            "value": "MRCHI",
            "type": "CONSTANT",
            "required": True,
            "start": 26,
            "end": 31,
            "length": 6,
        },
        "vendor_Document_number": {  ##invoice_number
            "source": "OCR",
            "type": "TEXT",
            "ocr_field": "invoice_number",
            "required": True,
            "start": 32,
            "end": 61,
            "length": 30,
        },
        "Group_ID": {
            "source": "predefined",
            "value": "",
            "type": "CONSTANT",
            "required": False,
            "start": 62,
            "end": 71,
            "length": 10,
        },
        "vendor_type": {
            "field_name": "Vendor Type",
            "source": "CONSTANT",
            "type": "TEXT",
            "value": "SUPP",
            "allowed_values": ["SUPP"],
            "required": True,
            "start": 72,
            "end": 77,
            "length": 6,
        },
        "vendor_id": {
            "field_name": "Vendor ID",
            "source": "WEB_SERVICE",
            "type": "NUMERIC",
            "required": True,
            "start": 78,
            "end": 87,
            "length": 10,
            "lookup": {"method": "PIN_CODE_AND_ADDRESS"},
            "user_correction_allowed": True,
        },
        "vendor_document_date": {  ##ocr_date
            "field_name": "Vendor Document Date",
            "source": "OCR",
            "ocr_field": "document_date",
            "type": "DATETIME",
            "required": True,
            "format": "YYYYMMDDHH24MISS",
            "start": 88,
            "end": 101,
            "length": 14,
        },
        "order_number": {
            "field_name": "Order Number",
            "ocr_field": "order_number",
            "source": "OCR",
            "type": "NUMERIC",
            "required": True,
            "start": 102,
            "end": 111,
            "length": 10,
            "lookup": {"method": "ORDER_NUMBER"},
        },
        "location": {
            "field_name": "Location",
            "source": "WEB_SERVICE",
            "type": "NUMERIC",
            "required": True,
            "start": 112,
            "end": 121,
            "length": 10,
            "lookup": {"method": "LOCATION_SERVICE"},
            "user_selection_required_if_multiple": True,
        },
        "Location_Type": {
            "type": "TEXT",
            "required": False,
            "start": 122,
            "end": 122,
            "length": 1,
        },
        "Terms": {
            "type": "TEXT",
            "required": False,
            "start": 123,
            "end": 137,
            "length": 15,
        },
        "DUE_DATE": {
            "field_name": "Due Date",
            "type": "DATETIME",
            "required": False,
            "format": "YYYYMMDDHH24MISS",
            "start": 138,
            "end": 151,
            "length": 14,
        },
        "Payment_Methods": {
            "type": "TEXT",
            "required": False,
            "start": 152,
            "end": 157,
            "length": 6,
        },
        "currency_code": {
            "field_name": "Currency Code",
            "ocr_field": "currency_code",
            "source": "OCR",
            "type": "ISO_CODE",
            "required": True,
            "start": 158,
            "end": 160,
            "length": 3,
        },
        "exchange_rate": {
            "field_name": "Exchange Rate",
            "type": "NUMERIC",
            "required": False,
            "start": 161,
            "end": 172,
            "length": 12,
        },
        "total_cost_sign": {
            "field_name": "Sign Indicator - Total Cost",
            "source": "PREDEFINED",
            "value": "+",
            "type": "CONSTANT",
            "required": True,
            "start": 173,
            "end": 173,
            "length": 1,
        },
        "total_cost": {
            "field_name": "Total Cost",
            "type": "NUMERIC",
            "required": False,
            "start": 174,
            "end": 193,
            "length": 20,
        },
        "total_vat_sign": {
            "field_name": "Sign Indicator - Total VAT",
            "source": "PREDEFINED",
            "value": "+",
            "type": "CONSTANT",
            "required": True,
            "start": 194,
            "end": 194,
            "length": 1,
        },
        "total_vat_amount": {
            "field_name": "Total VAT Amount",
            "type": "NUMERIC_DECIMAL",
            "required": False,
            "start": 195,
            "end": 214,
            "length": 20,
        },
        "total_quantity_sign": {
            "field_name": "Sign Indicator - Total Quantity",
            "source": "PREDEFINED",
            "value": "+",
            "type": "CONSTANT",
            "required": True,
            "start": 215,
            "end": 215,
            "length": 1,
        },
        "total_quantity": {
            "field_name": "Total Quantity",
            "source": "OCR",
            "ocr_field": "item_total_quantity",
            "type": "NUMERIC_DECIMAL",
            "required": True,
            "start": 216,
            "end": 227,
            "length": 12,
            "decimal_places": 4,
            "implied_decimals": True,
        },
        "total_discount_sign": {
            "field_name": "Sign Indicator - Total Discount",
            "source": "PREDEFINED",
            "value": "+",
            "type": "CONSTANT",
            "required": True,
            "start": 228,
            "end": 228,
            "length": 1,
        },
        "total_discount": {
            "field_name": "Total Discount",
            "source": "OCR",
            "type": "NUMERIC_DECIMAL",
            "required": True,
            "start": 229,
            "end": 240,
            "length": 12,
            "decimal_places": 4,
            "implied_decimals": True,
        },
        "freight_type": {
            "field_name": "Freight Type",
            "source": "WEB_SERVICE",
            "type": "TEXT",
            "required": False,
            "start": 241,
            "end": 246,
            "length": 6,
        },
        "paid_indicator": {
            "field_name": "Paid Indicator",
            "source": "PREDEFINED",
            "value": "N",
            "type": "CONSTANT",
            "required": True,
            "start": 247,
            "end": 247,
            "length": 1,
        },
        "multi_location_indicator": {
            "field_name": "Multi Location Indicator",
            "source": "PREDEFINED",
            "value": "N",
            "type": "CONSTANT",
            "required": True,
            "start": 248,
            "end": 248,
            "length": 1,
        },
        "merchandise_type": {
            "field_name": "Consignment / Merchandise Type",
            "source": "PREDEFINED",
            "value": "E",
            "type": "CONSTANT",
            "required": True,
            "start": 249,
            "end": 249,
            "length": 1,
            "allowed_values": ["C", "D", "E"],
        },
        "deal_id": {
            "field_name": "Deal ID",
            "source": "WEB_SERVICE",
            "type": "NUMERIC",
            "required": False,
            "start": 250,
            "end": 259,
            "length": 10,
        },
        "deal_approval_indicator": {
            "field_name": "Deal Approval Indicator",
            "source": "WEB_SERVICE",
            "type": "TEXT",
            "required": False,
            "start": 260,
            "end": 260,
            "length": 1,
            "allowed_values": ["M", "A"],
        },
        "rtv_indicator": {
            "field_name": "RTV Indicator",
            "source": "PREDEFINED",
            "value": "N",
            "type": "CONSTANT",
            "required": True,
            "start": 261,
            "end": 261,
            "length": 1,
        },
        "custom_reference_1": {
            "field_name": "Custom Document Reference 1",
            "type": "TEXT",
            "required": False,
            "start": 262,
            "end": 351,
            "length": 90,
        },
        "custom_reference_2": {
            "field_name": "Custom Document Reference 2",
            "type": "TEXT",
            "required": False,
            "start": 352,
            "end": 441,
            "length": 90,
        },
        "custom_reference_3": {
            "field_name": "Custom Document Reference 3",
            "type": "TEXT",
            "required": False,
            "start": 442,
            "end": 531,
            "length": 90,
        },
        "custom_reference_4": {
            "field_name": "Custom Document Reference 4",
            "type": "TEXT",
            "required": False,
            "start": 532,
            "end": 621,
            "length": 90,
        },
        "cross_reference_document_number": {
            "field_name": "Cross-Reference Document Number",
            "source": "OCR",
            "type": "NUMERIC",
            "required": False,
            "start": 622,
            "end": 631,
            "length": 10,
        },
    }
}
