PREDEFINED_FIELDS = {
    "ttail": {
        "record_descriptor": {
            "field_name": "Record Descriptor",
            "source": "PREDEFINED",
            "type": "CONSTANT",
            "value": "TTAIL",
            "start": 1,
            "end": 5,
            "length": 5,
            "required": True,
        },
        "line_id": {
            "field_name": "Line ID",
            "source": "SEQUENCE",
            "type": "FILE_SEQUENCE",
            "start": 6,
            "end": 15,
            "length": 10,
            "format": "ZERO_PADDED",
            "required": True,
        },
        "transaction_number": {
            "field_name": "Transaction Number",
            "source": "TRANSACTION_SEQUENCE",
            "type": "TRANSACTION",
            "start": 16,
            "end": 25,
            "length": 10,
            "format": "ZERO_PADDED",
            "required": True,
        },
        "transactions_lines": {
            "field_name": "Transaction Lines",
            "source": "CALCULATED",
            "type": "Numeric",
            "start": 26,
            "end": 31,
            "length": 6,
            "required": True,
            "calculation": "COUNT_DETAIL_LINES",
        },
    },
}
