PREDEFINED_FIELDS = {
    "tvats": {
        "record_descriptor": {
            "field_name": "Record Descriptor",
            "source": "PREDEFINED",
            "type": "CONSTANT",
            "value": "TVATS",
            "start": 1,
            "end": 5,
            "length": 5,
            "required": True,
        },
        "line_id": {
            "field_name": "Line ID",
            "source": "SEQUENCE",
            "type": "FILE_SEQUENCE",
            "start": 6,
            "end": 15,
            "length": 10,
            "format": "ZERO_PADDED",
            "required": True,
        },
        "transaction_number": {
            "field_name": "Transaction Number",
            "source": "TRANSACTION_SEQUENCE",
            "type": "TRANSACTION",
            "start": 16,
            "end": 25,
            "length": 10,
            "format": "ZERO_PADDED",
            "required": True,
        },
        "vat_code": {
            "field_name": "VAT Code",
            "source": "WEB_SERVICE",
            "type": "TEXT",
            "start": 26,
            "end": 31,
            "length": 6,
            "required": True,
        },
        "vat_rate": {
            "field_name": "VAT Rate",
            "source": "WEB_SERVICE",
            "type": "NUMERIC_DECIMAL",
            "start": 32,
            "end": 51,
            "length": 20,
            "decimal_places": 10,
            "implied_decimals": True,
            "required": True,
        },
        "cost_sign": {
            "field_name": "Sign Indicator - Cost",
            "source": "PREDEFINED",
            "type": "CONSTANT",
            "value": "+",
            "start": 52,
            "end": 52,
            "length": 1,
            "required": True,
        },
        "cost_at_vat_code": {
            "field_name": "Cost at this VAT Code",
            "source": "WEB_SERVICE",
            "type": "NUMERIC_DECIMAL",
            "start": 53,
            "end": 72,
            "length": 20,
            "decimal_places": 4,
            "implied_decimals": True,
            "required": True,
        },
    },
}
